### ISSUE TITLE
Unity (Game Engine) Yaml parsing

### ISSUE THREAD

**Issue by ArcoMul** [nodeca/js-yaml#100]
Hello,

I am trying to parse meta files from the game engine Unity to Json. (For a kind of self build level editor), now I try to parse the Yaml data with JS-Yaml, but I get an error.

The following Yaml:

```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!1 &100000
GameObject:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  serializedVersion: 4
  m_Component:
  - 4: {fileID: 400000}
  - 212: {fileID: 21200000}
  - 61: {fileID: 6100000}
  - 50: {fileID: 5000000}
  - 114: {fileID: 11400001}
  m_Layer: 14
  m_Name: CamelGreen
  m_TagString: Plane
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 0
  m_IsActive: 1
--- !u!1 &100002
...
```

Throws the error:

```
JS-YAML: unknown tag !<tag:unity3d.com,2011:1> at line 22, column 1:
    --- !u!1 &100002
    ^

...\node_modules\js-yaml\lib\js-yaml\loader.js:154
    throw generateError(message);
          ^
YAMLException: JS-YAML: undeclared tag handle "!u!" at line 22, column 9:
    --- !u!1 &100002
```

But as far as my limited knowledge about Yaml goes, I do see a TAG declaration at the top of the Yaml file.

Then I tried to declare a custom tag:

```
var spaceYamlType = new yaml.Type('!u!', {
  loader: {
    kind: 'object',
    resolver: function (object) {
      return object;
    }
  },
  dumper: {
    kind: 'object',
    instanceOf: Object 
  }
});

var SPACE_SCHEMA = yaml.Schema.create([ spaceYamlType ]);
```

_(Yes, that is code straight copied from the example)_
But that didn't work either (same error).

Any idea what is going wrong here?

_Arco_
