### ISSUE TITLE
[dumper] Unnecessary quoting for strings with internal dashes

### ISSUE THREAD

**Issue by puzrin** [nodeca/js-yaml#104]
Dumper add quotes to all strings that have `-`. Seems, `css` property value quotes can be skipped without problems (al least, it's ok when i delete those manually):

``` yaml
glyphs: 
  - css: "day-cloudy-gusts"
    code: 0xE800
    uid: c77de216fba51e29c6fc03012d4d5973
    search: [day, cloudy, gusts, wind, windy]
```

Can that be improved without serious yaml rewrite?
