### ISSUE TITLE
[Question] validating 'empty/null' 

### ISSUE THREAD

**Issue by zepedrorocha** [nodeca/js-yaml#168]
Example:
```yaml
dialogueSystem:
  actors:
  - id: 1
    fields:
    - title: Name
      value: Marcelo
      type: 0
    - title: Description
      value: 
      type: 0
    - title: IsPlayer
      value: true
      type: 2
```
After using safeLoad() and safeDump() I get the folowing:
```yaml
dialogueSystem:
  actors:
  - id: 1
    fields:
    - title: Name
      value: Marcelo
      type: 0
    - title: Description
      value: null
      type: 0
    - title: IsPlayer
      value: true
      type: 2
```

The empty ***'value: '*** was set to ***'value: null'*** 
should safeDump option 'styles' have ***''*** option  (instead of 'null') ? Am I doing something wrong ? 

Thanks
