### ISSUE TITLE
Multiline flow scalar is triggering error

### ISSUE THREAD

**Issue by gsound** [nodeca/js-yaml#170]
According to [YAML specs] (http://www.yaml.org/spec/1.2/spec.html#id2760844) multiline flow scalar is valid and js-yaml is triggering an error.

Sample YML:
```yaml
level1:
  level2:
     level3: "this is a multiline
value. And it is a valid
yaml"
```

error:
```js
JS-YAML: deficient indentation at line X, column Y:
```

**Comment by puzrin** [comment]
You need to use proper identation.

```yaml
level1:
  level2:
     level3: "this is a multiline
       value. And it is a valid
       yaml"
```
