### ISSUE TITLE
object at depth not converted

### ISSUE THREAD

**Issue by scottnath** [nodeca/js-yaml#176]
Using version 3.2.7 of js-yaml

## problem
When I try to convert yaml to a javascript object, internal objects are displayed as `[Object]`, but this is not happening in your [demo](http://nodeca.github.io/js-yaml/).

## my yaml
```
levels:
  level-one:
    - file1
    - file2
  level-two:
    - file1
    - file2
    - dir1:
      - file1
      - file2
```

## my code
```
var str = 'levels:\n'+
'  level-one:\n'+
'    - file1\n'+
'    - file2\n'+
'  level-two:\n'+
'    - file1\n'+
'    - file2\n'+
'    - dir1:\n'+
'      - file1\n'+
'      - file2';
var test = yaml.load(str);
console.log(test);
```

## result from my code
```
{ levels:
   { 'level-one': [ 'file1', 'file2' ],
     'level-two': [ 'file1', 'file2', [Object] ] } }
```

## result from your demo
```
{ levels: 
   { 'level-one': [ 'file1', 'file2' ],
     'level-two': [ 'file1', 'file2', { dir1: [ 'file1', 'file2' ] } ] }
```

Do I need to implement code like in your [util file](https://github.com/nodeca/js-yaml/blob/gh-pages/js/utils.js) in order to get this working correctly? Is there a more straightforward way?

thanks
Scott
