### ISSUE TITLE
Whitespace not ignored with curly braces

### ISSUE THREAD

**Issue by jnu** [nodeca/js-yaml#194]
```yaml
foo: {
    bar: true
}
```

gives the warning `deficient indentation at line 3, column 1: }`

expect this to parse the same as
```yaml
foo: { bar: true }
```

Can work around for now by passing `{ onWarning: function() {} }`.
