### ISSUE TITLE
yaml to json and reverse with object names

### ISSUE THREAD

**Issue by dvirhazout** [nodeca/js-yaml#199]
Can't seem to find a solution using js-yaml for turning yaml to json with object names. then make the reverse operation and get expected result.

```yaml
--- !ruby/object:Page
title: Page title
sections:
- !ruby/object:Section
  components:
  - !ruby/object:Gallery
    children_components:
    - !ruby/object:Panel
      background: !ruby/object:ImageComponent
        url: img.jpg
```

What I've tried to do so far is manipulate the yaml string but that messy and ugly.
