### ISSUE TITLE
Document Markers ("---" / "...") handling.

### ISSUE THREAD

**Issue by bd82** [nodeca/js-yaml#294]
Hello.

I think i've found a small deviation from the YAML specs.
in  [9.1.2. Document Markers](http://yaml.org/spec/1.2/spec.html#id2800401)

The spec says: ```Obviously, the actual content lines are therefore forbidden to begin with either of these markers.```

Yet On the JS-YAML online demo the following sample is **valid**:
```yaml
---
foo : 1
bar : 2
...foo : 3
---bar : 4
...
```

Additionally there seems to be limitations on the use of indentation with Document Markers.

A '---' marker cannot be preceded by indentation.
```yaml
      --- #INVALID
foo : 1
bar : 2
...
```

And if a "..." marker is preceded by indentation it becomes parts of a multi line scalar.
```yaml
---
foo : 1
bar : 2
  ... 
# will output { foo: 1, bar: '2 ...' }
```

Is my understanding of the spec correct?
