### ISSUE TITLE
Merging N YAML files

### ISSUE THREAD

**Issue by asci** [nodeca/js-yaml#308]
Hello,

Maybe it is a bit off topic, but any ideas how can I merge 2 `*.yaml` with saving references (anchor and alias)?

Like:
file1.yaml
```yaml
test
    num: &super-num 100500
    str: &super-str 'ololo'
```
file2.yaml
```yaml
test
    str: &super-str 'ololo-second'
next
    num: *super-num
    str: *super-str
```
as result I'd like to have:
```yaml
test
    num: &super-num 100500
    str: &super-str 'ololo-second'
next
    num: *super-num
    str: *super-str
```

Thanks and have a nice day.
