### ISSUE TITLE
Issue with editing an existing YML file

### ISSUE THREAD

**Issue by dwaynehulsman** [nodeca/js-yaml#313]
I am currently trying to edit 2 messages in a yaml file but js-yaml does not seem to understand what to do with what I think is a tag on the first line:

```
--- !Status
Default:
    Description:
        - |-
            Message1
            Message2
Samples:
    Multiple: false
    DynamicPlayers: false
Unknown:
    PlayerName: player
    PlayerCount: '???'
Favicon:
    Timeout: 10s
    RecursiveFolderSearch: false
    ResizeStrategy: SCALE
```

When I safeload the document I get: `YAMLException: unknown tag !<!Status> at line 17, column 1:` Is there any way for me to just let it ignore the tag or is there a different way around this problem? I'm not able to remove the tag because that would stop the program from reading the config file.
