### ISSUE TITLE
Unexpected quotations when dumping

### ISSUE THREAD

**Issue by lbauret** [nodeca/js-yaml#320]
When dumping the following JSON, it seems there are some specific situations where strings are not held between quotation marks. For example when a certain string starts with 0, or "08" and "09" strings. Also, strings are not properly indented when containing \t or \r.

Input:
```json
{
  "start-with-0" : {
    "fails": "015678",
    "ok": "115678"
  },
  "number-list" : [
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11"
  ],
  "white-spaces": {
    "string1": "**Hello World**\n\n**Sample Text.** \t End of text.",
    "string2": "**Hello World**\n\n**Sample Text.** \r End of text.",
    "string3": "**Hello World**\n\n**Sample Text.**  End of text.",
  }
}
```

Output:
```yaml
start-with-0:
  fails: 015678
  ok: '115678'
number-list:
  - '01'
  - '02'
  - '03'
  - '04'
  - '05'
  - '06'
  - '07'
  - 08
  - 09
  - '10'
  - '11'
white-spaces:
  string1: "**Hello World**\n\n**Sample Text.** \t End of text."
  string2: "**Hello World**\n\n**Sample Text.** \r End of text."
  string3: |-
    **Hello World**

    **Sample Text.**  End of text.
```
