### ISSUE TITLE
jsyaml.safeDump crashes if data set contains # (hash sign)

### ISSUE THREAD

**Issue by AresSec** [nodeca/js-yaml#323]
Version: 3.7.0

If the data you want to dump into a yaml with execute jsyaml.safeDump(data) and the data contains a hash sign # , for e.g. a link with an anchor and you:

www.foobar.com/test#subchapter

The yaml file will be written but only until www.foobar.com/test and ends there. Afterwards it's not a valid yaml file anymore and you can't import it via safeLoad anymore.

**Comment by puzrin** [comment]
@AresSec links are broken. Could you post code sample here, to reproduce this bug?

**Comment by shockey** [comment]
@AresSec You can work around this by wrapping your strings with single or double quotes.

**Comment by puzrin** [comment]
```js
console.log(yaml.safeDump('www.foobar.com/test#subchapter'));
// => www.foobar.com/test#subchapter
console.log(yaml.safeDump({ a: 'www.foobar.com/test#subchapter', b: 123 }));
// =>
// a: 'www.foobar.com/test#subchapter'
// b: 123
```

I can not reproduce this error. Please, provide code sample to keep issue open.

**Comment by AresSec** [comment]
I've created a sample object. Code:
```javascript
if ($scope.extension === 'yaml') {
                                        var file = $scope.buildYAMLFile();
                                        var mime = "data:application/x-yaml;charset=utf-8,";
                                        var ext = ".yml";
                                        console.log(file);
                                        var doc = jsyaml.safeDump(file);
                                        var a = document.createElement('a');
```
Console output:
![objects_console](https://cloud.githubusercontent.com/assets/19144234/22626622/3f25fbfa-ebb2-11e6-94b5-b6710b980bf6.png)

File output (I ommited the first parts due to the length):
```
- id: 2
        shortName: LC-01
        showOrder: 10
        universalId: ''
        description: Appoint the Security Mentor role.
        ticket: ''
        tagInstances:
          - 17
          - 5
        optColumns:
          - content:
              - id: 0
                content: 'In case your Security Mentor is not known, please ask the IT security department (http://test.com/
```

It actually only process until the hashsign of the URL (value is (http://test.com/#foobar)). Output stops directly after test.com/

I don't see any error ins the console from js-yaml. It just's process the object and creates the yaml file like nothing went wrong.
