### ISSUE TITLE
Using the << syntax

### ISSUE THREAD

**Issue by simlu** [nodeca/js-yaml#390]
I'm trying to use the `<<` syntax. Is this currently supported?

My input is
```yml
  environment:
    STAGE: some-stage
    <<: ${file(config/file.yml)
```
but no luck.

Would very much appreciate some help! Thank you!

**Comment by rlidwka** [comment]
Merging is supported, e.g.:

```yaml
- &foo
  x: 1
  y: 2
- <<: *foo
  z: 3
```

is translated into `[ { x: 1, y: 2 }, { x: 1, y: 2, z: 3 } ]`.

As for `${file(...)}` - this looks like a job for a pre-processor, not yaml parser. Something like this would work:

```js
yaml.load(str.replace(/\$\{(.*?)\}/g, (_, x) => eval(x)));
```
