### ISSUE TITLE
Problem using "<<" with ordered maps

### ISSUE THREAD

**Issue by alqu** [nodeca/js-yaml#408]
Hi,

maybe I am doing something wrong here, but the code below works with a PHP-based YAML parser, but not here.

So this works:

```yaml
products:
- id: 1
  items: &prod1
    - attrib: foo
    - attrib: bar

- id: 2
  items: *prod1
```
[Fiddle](http://nodeca.github.io/js-yaml/#yaml=cHJvZHVjdHM6Ci0gaWQ6IDEKICBpdGVtczogJnByb2QxCiAgICAtIGF0dHJpYjogZm9vCiAgICAtIGF0dHJpYjogYmFyCgotIGlkOiAyCiAgaXRlbXM6ICpwcm9kMQ==)

But when I try to merge because I need to add more attribs, then this fails:
```yaml
products:
- id: 1
  items: &prod1
    - attrib: foo
    - attrib: bar

- id: 2
  items:
    <<: *prod1
    - attrib: baz
```
[Fiddle](http://nodeca.github.io/js-yaml/#yaml=cHJvZHVjdHM6Ci0gaWQ6IDEKICBpdGVtczogJnByb2QxCiAgICAtIGF0dHJpYjogZm9vCiAgICAtIGF0dHJpYjogYmFyCgotIGlkOiAyCiAgaXRlbXM6CiAgICA8PDogKnByb2QxCiAgICAtIGF0dHJpYjogYmF6)

Error message: "bad indentation of a mapping entry at ... - attrib: baz"

The expected **result** should be a list of items that contain foo, bar and baz, just like
```yaml
products:
# ...
- id: 2
  items:
    - attrib: foo
    - attrib: bar
    - attrib: baz
```

What am I doing wrong?
