### ISSUE TITLE
noRef option doesn't work

### ISSUE THREAD

**Issue by giniz** [nodeca/js-yaml#425]
Here are my yaml after dumped, the duplicates weren't replaced with ref:

```
Profiles:
  channel1:
    - Name: org1
      ID: org1MSP
      AdminPrincipal: ROLE.ADMIN
      AnchorPeers: []
    - Name: org2
      ID: org2MSP
      AdminPrincipal: ROLE.ADMIN
      AnchorPeers: []
  network1genesis:
    Orderer:
      Addresses:
        - '127.0.0.1:7050'
      BatchTimeout: 2s
      Kafka:
        Brokers:
          - 'kafka0:9092'
          - 'kafka1:9093'
      Organizations:
        - Name: ordererOrg
          ID: ordererOrgMSP
          AdminPrincipal: ROLE.ADMIN
          AnchorPeers: []
      Capabilities:
        V1_1: true
    Consortiums:
      channel1:
        - Name: org1
          ID: org1MSP
          AdminPrincipal: ROLE.ADMIN
          AnchorPeers: []
        - Name: org2
          ID: org2MSP
          AdminPrincipal: ROLE.ADMIN
          AnchorPeers: []
Organizations:
  - Name: org1
    ID: org1MSP
    AdminPrincipal: ROLE.ADMIN
    AnchorPeers: []
  - Name: org2
    ID: org2MSP
    AdminPrincipal: ROLE.ADMIN
    AnchorPeers: []
  - Name: ordererOrg
    ID: ordererOrgMSP
    AdminPrincipal: ROLE.ADMIN
    AnchorPeers: []
Application:
  Organizations:
    - Name: org1
      ID: org1MSP
      AdminPrincipal: ROLE.ADMIN
      AnchorPeers: []
    - Name: org2
      ID: org2MSP
      AdminPrincipal: ROLE.ADMIN
      AnchorPeers: []
  Capabilities:
    V1_1: true
```
