### ISSUE TITLE
Formatting options

### ISSUE THREAD

**Issue by Superpencil** [nodeca/js-yaml#430]
I'm trying to match the formatting of the dumper to pass tests performed by https://github.com/glebm/i18n-tasks, is there a way to change the configuration for the three items below? Thank you for reading!

- Double quotes become single quotes here (It expects double due to the `%{}`)
  ```yml
  rule: " %{pay} 入金すると %{days} 日後に %{get} のボーナス付与 "
  ```
  ```yml
  rule: ' %{pay} 入金すると %{days} 日後に %{get} のボーナス付与 '
  ```
- Quotes added around items with a comma:
  ```yml
  return_document:
    button: Extra documentation?
    content: If the store requires any extra documents, upload them here.
    title: Any extra documentation required?
  ```
  ```yml
  return_document:
    button: Extra documentation?
    content: 'If the store requires any extra documents, upload them here.'
    title: Any extra documentation required?
  ```
- Quotes removed from strings containing xml:
  ```yml
  title: "<i class='mdi mdi-glass-tulip'></i> 氣泡襯墊"
  ```
  ```yml
  title: <i class='mdi mdi-glass-tulip'></i> 氣泡襯墊
  ```
