### ISSUE TITLE
custom types with multiple kind

### ISSUE THREAD

**Issue by qraynaud** [nodeca/js-yaml#434]
I'm wondering if it would be possible / very difficult to allow custom types to have multiple kinds. I often have the issue of having both a "naive" scalar representation and a more complex mapping one.

That might look like for your `Point` exemple:

```yaml
someValue: !point
- 12
- 21
- 42
someIdenticalValue: !point
  x: 12
  y: 21
  z: 42
```

It would be very cool if it was possible either to pass an array for kind instead or simply omit it.

```js
class Point {
  constructor(data) {
    if (!data.x) {
      data = {x: data[0], y: data[1], z: data[2]}

    this.klass = 'Point';
    this.x = data.x
    this.y = data.y
    this.z = data.z
  }

  // …
}

var PointYamlType = new yaml.Type('!point', {
  kind: ['sequence', 'mapping'], // either a sequence or a mapping
  resolve: data => data !== null && (data.x && data.y && data.z || data.length === 3)
  construct: data => new Point(data),
  // …
}
```

It might be a good idea to provide kind as a 2nd argument to allow for safer/cleaner code:

```js
class Point {
  constructor(data) {
    this.klass = 'Point';
    this.x = data.x
    this.y = data.y
    this.z = data.z
  }

  // …
}

var PointYamlType = new yaml.Type('!point', {
  kind: ['sequence', 'mapping'],
  resolve: (data, kind) =>
    data !== null && data.kind === 'sequence' ?
      data.length === 3 :
      data.x && data.y && data.z,
  construct: (data, kind) => {
    if (kind === 'sequence')
      data = {x: data[0], y: data[1], z: data[2]}
    return new Point(data)
  },
  // …
}
```

What would be your thoughts about this?

**Comment by puzrin** [comment]
1. As far as i remember, we have to use simple structures for performance reasons. So, allowing "kind" to be polymorphic (both literal and array) does not looks like attractive idea.
2. Adding `kind` as second param o resolve/construct looks like "kluge":
   - From dataflow's point of view, pinning second param to 'kind' looks strange
   - Last example does not looks good for me, because code inside will be always polymorphyc. That may work, but suspicious at architecture design level.

So, i can understand desire to simplify population of custom tags, but i'm skeptical about way you wish to solve it. May be you have another ideas?

**Comment by qraynaud** [comment]
1. we could add a `kinds` attribute in that case, the user would either provide `kind` with a string or `kinds` with an array of strings
2. if kinds is used, we could call `resolve[Mapping|Scalar|Sequence]()` and `construct[Mapping|Scalar|Sequence]()` methods instead

That would look like:
```js
class Point {
  constructor(data) {
    this.klass = 'Point';
    this.x = data.x
    this.y = data.y
    this.z = data.z
  }

  // …
}

var PointYamlType = new yaml.Type('!point', {
  kinds: ['sequence', 'mapping'],
  resolveSequence: data => data !== null && data.length === 3,
  resolveMapping: data => data !== null && data.x && data.y && data.z,
  constructSequence: data => new Point({x: data[0], y: data[1], z: data[2]}),
  constructMapping: data => new Point(data),
  // …
}
```

**Comment by qraynaud** [comment]
By the way, one of my true usage would be something like this:

```yaml
port: !env NODE_ENV   # just read the NODE_ENV environment variable
port2: !env
  name: NODE_ENV      # do the same but also:
  type: Number        # - cast it to a Number if it was set
  default_value: 3000 # - or set its value to 3000 if it was empty
```

That would tremendously simplify some of my config files. Right now the same thing looks like:
```yaml
port2: !cast
  value: !default
    value: !env NODE_ENV
    default: 3000
  type: Number
```

**Comment by puzrin** [comment]
I do not understand you point. Do you suggest to create container, which can store  multiple simple types and have constructor interface like for simple type? Such thing would be very confusing. Why not just create your own helper, to add multiple types at once?

**Comment by qraynaud** [comment]
I don't understand your question. What are you referring to specifically?

**Comment by puzrin** [comment]
Let's start from the begining.

- Do i understand right, that you have custom objects with dual formats, and would like simplify methods to define those?
- What alternate method do you like to have and how much will it save, compared to existing one?

**Comment by qraynaud** [comment]
1. Yes, that's seems right to me
2. I described what I do now in my comment https://github.com/nodeca/js-yaml/issues/434#issuecomment-409946077

I don't like it because:
  * it makes every file a lot harder to read & write
  * it is harder to debug

What I would like to be able to write would be:
```js

var PointYamlType = new yaml.Type('!env', {
  kinds: ['scalar', 'mapping'],
  resolveFromScalar: data => _.isString(data),
  resolveFromMapping: data => data !== null && _.isString(data.name),
  constructFromScalar: name => new Env({name}),
  constructFromMapping: data => new Env(data),
  // …
}
```

**Comment by puzrin** [comment]
Not enougth info about this question:

> and how much will it save

IMHO some added value exists, but not enougth for suggested changes.

**Comment by julien-c** [comment]
Why don't you just define two ≠ custom types?
```yaml
port: !env NODE_ENV   # just read the NODE_ENV environment variable
port2: !oenv
  name: NODE_ENV      # do the same but also:
  type: Number        # - cast it to a Number if it was set
  default_value: 3000 # - or set its value to 3000 if it was empty
```

**Comment by qraynaud** [comment]
@julien-c Because:
1/ It is hard to remember from a user PoV
2/ It is a very bad design practice to have 2 types that maps to the same internal structure/type: we are in a classic case of different constructors for the same type eg:

```js
const port = new Env('NODE_PORT')
const port2 = new Env({name: 'NODE_PORT', type: 'Number', defaultValue: 3000})
```

You would never suggest to me to have 2 ≠ types in JS to achieve this use case (or at least I want to believe you would not).

**Comment by qraynaud** [comment]
@puzrin : can you be more specific about what kind of savings you are referring to? I'm not sure I understand your meaning there. I'll try with my idea of what you might mean.

For me, it saves multiple custom types declarations like described by @julien-c that are really ugly because you get to have multiple YAML types that maps to the same JS type. It is also counter intuitive to change the type name only because you want to be more specific about your type declaration at some point. Or propose different representation of the same type (like a show cased for `Point` first hand). It would also make sense for GPS points that usually have 3 possible representations:

```yaml
geo1: !geo-point '48.8589101,2.3120407'
geo2: !geo-point
  lat: 48.8589101
  lon: 2.3120407
geo3: !geo-point
- 2.3120407
- 48.8589101
```

If this is a very hard to do change, I'm okay about not doing it. It might not be worth the effort. But if it's not long to do, I might be okay to do the changes myself if you are willing to point me in the right direction. I really think this would make sense and be a nice addition to the lib. At least I would use it a lot. I've been hurt by this on more than one occasion already!
