### ISSUE TITLE
Invalid parsing of double quote string

### ISSUE THREAD

**Issue by meeroslav** [nodeca/js-yaml#458]
If I have a following yaml:
```yaml
pipeline:
  notify:
     env: "development",
     token: ${TOKEN},
     command:
       - npm run lint
       - npm run build:ci
```

after running `yaml.safeLoad` and `yaml.safeDump` I end up with:

```yaml
pipeline:
  notify:
     env: development,
     token: '${TOKEN}',
     command:
       - npm run lint
       - 'npm run build:ci'
```

The development double quotes get lost during the safeLoad and token and command (but only those with `:` receive single quotes on safeDump.

I would expect running those two operations not to mutate my yaml data.
