### ISSUE TITLE
I do I turn off the escaping/quoting about `C#` for a name field? 

### ISSUE THREAD

**Issue by diberry** [nodeca/js-yaml#466]
The original TOC looks like:

```
- name: LUIS Documentation
  href: index.yml
- name: Overview
  expanded: true
  items:
  - name: C#
    href: what-is-luis.md
```

I want to manipulate the yaml so I change in into JSON with load. Then I check and manipulate (business logic) then I want to dump. The dump adds quotes around the C# which I don't want. Is there an option to turn that off? 

- name: LUIS Documentation
  href: index.yml
- name: Overview
  expanded: true
  items:
  - name: "C#"
    href: what-is-luis.md
```
