### ISSUE TITLE
How do I turn off line folding for the .dump call? 

### ISSUE THREAD

**Issue by diberry** [nodeca/js-yaml#467]
How do I stop 'dump' from adding '>-" and the new line when calling dump?

Original markdown

```
- name: LUIS Documentation
  href: index.yml
- name: Overview
  expanded: true
  items:
  - name: C#
    href: https://cognitive.uservoice.com/knowledgebase/topics/asdfasdfasdfasdfasdfasdf/127872-luis-language-understanding-intelligent-service
```

yaml.dump markdown

```
- name: LUIS Documentation
  href: index.yml
- name: Overview
  expanded: true
  items:
    - name: 'C#'
      href: >-
        https://cognitive.uservoice.com/knowledgebase/topics/asdfasdfasdfasdfasdfasdf/127872-luis-language-understanding-intelligent-service
```
