### ISSUE TITLE
How to control indents via param options to dump?

### ISSUE THREAD

**Issue by diberry** [nodeca/js-yaml#468]
An extra 2 spaces is getting added on the item "C#" and its href. How do I turn this off? 

original yaml:

`- name: LUIS Documentation
  href: index.yml
- name: Overview
  expanded: true
  items:
  - name: C#
    href: https://cognitive.uservoice.com/knowledgebase/topics/asdfasdfasdfasdfasdfasdf/127872-luis-language-understanding-intelligent-service`

Final yaml where last 2 lines have additional (but unwanted) 2 spaces:

`- name: LUIS Documentation
  href: index.yml
- name: Overview
  expanded: true
  items:
    - name: 'C#'
      href: 'https://cognitive.uservoice.com/knowledgebase/topics/asdfasdfasdfasdfasdfasdf/127872-luis-language-understanding-intelligent-service'`

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml#safedump-object---options-

`noArrayIndent` ?

**Comment by diberry** [comment]
Here are all my options, I toggled noArrayIndent and the results are in the screenshot. Left = original

`
options={
            "skipInvalid":false,
            "noCompatMode":false,
            "sortKeys":false,
            "lineWidth":3000,
            "noArrayIndent":false,
            "noRefs":true,
            "flowLevel":-1,
            "condenseFlow":false
        }
`

![no-array-index-results](https://user-images.githubusercontent.com/41597107/52958567-2e10e880-3349-11e9-9a6c-54796facd9c4.PNG)

**Comment by puzrin** [comment]
Is this this a question or not? Is this issue solved?

**Comment by perlpunk** [comment]
@diberry could you paste your results as text instead of a screenshot? just put three backticks in one line
before and after the pasted snippet. or indent the whle snippet with 4 spaces. makes it easier to copy snippets and try them out.

@puzrin it looks like a bug to me. in the picture on the right the YAML seems invalid. items like `href: ...` in line 2 and `expanded: ...` in line 4 have no indent

**Comment by diberry** [comment]
@perlpunk Thanks for the pointer.

original 

```
- name: LUIS Documentation
  href: index.yml
- name: Overview
  expanded: true
  items:
  - name: C#
    href: https://cognitive.uservoice.com/knowledgebase/topics/asdfasdfasdfasdfasdfasdf/127872-luis-language-understanding-intelligent-service
```

"noArrayIndent"= false

```
- name: LUIS Documentation
  href: index.yml
- name: Overview
  expanded: true
  items:
    - name: 'C#'
      href: 'https://cognitive.uservoice.com/knowledgebase/topics/asdfasdfasdfasdfasdfasdf/127872-luis-language-understanding-intelligent-service'
```

"noArrayIndent"=true

```
- name: LUIS Documentation
href: index.yml
- name: Overview
expanded: true
items:
- name: 'C#'
  href: 'https://cognitive.uservoice.com/knowledgebase/topics/asdfasdfasdfasdfasdfasdf/127872-luis-language-understanding-intelligent-service'

```
