### ISSUE TITLE
First item in a !!pair is unnecessarily converted into string

### ISSUE THREAD

**Issue by rlidwka** [nodeca/js-yaml#481]
```yaml
pairs:
  Block tasks: !!pairs
    - { test: 123 }: { test: 123 }
    - { test: 456 }: { test: 456 }
```

```json
{ pairs: 
   { 'Block tasks': 
      [ [ '[object Object]', { test: 123 } ],
        [ '[object Object]', { test: 456 } ] ] } }
```

In normal maps `{ test: 123 }` is turned into string because javascript doesn't support objects as keys (Maps aside, as we don't support those).

But pairs are turned into arrays, which *can* have objects inside. So stringification is unnecessary there.

*somewhat related to #169, but this is an issue that can be fixed without rewriting everything*
