### ISSUE TITLE
Not able to generate anchor references using safeDump

### ISSUE THREAD

**Issue by voelkl** [nodeca/js-yaml#486]
So I am converting a json file to a yml file using safeDump

so the outcome is like this
```
en:
  models: 
    errors:
      name: name not found
      url: bad url
  user: 
    errors:
      name: name not found
      url: bad url
  photo:
    errors:
      name: name not found
      url: bad url
```
but I am not able to generate the anchor references
```
en:
  models: 
    errors: &1
      name: name not found
      url: bad url
  user:
    errors: *1
  photo:
    errors: *1
```
Is there any way to add an option to the method?
I tried the option noRefs: false but it is not working. I would appreciate if you could help me find a solution.
