### ISSUE TITLE
2d array formatting

### ISSUE THREAD

**Issue by davidejones** [nodeca/js-yaml#487]
Not sure if this is a bug or a configuration problem on my end, perhaps someone can help.

If i take a nested array/list like in the `nested_array` variable below and run it through load and then dump it back out it causes the first array hyphen `-` to no longer have new lines and appear on the same line giving me `--`.  

I don't really care how it looks however this yaml is loaded into [Hugo](https://github.com/gohugoio/hugo) which doesn't appear to like this format. So i'd need it to dump out the way it went in but i can't seem to find any option that gives me this.

Is it part of the yaml spec to have it output this way or is this a bug?

```javascript
const yaml = require("js-yaml");
const nested_array = `
team:
  -
    - bio: this is a test
      name: another test
    - bio: second item
      name: foo bar 2
  -
    - bio: another
      name: another
`;
const data = yaml.load(nested_array);
console.log(data);
console.log(yaml.safeDump(data));
```

I get the following output

```
{ team: [ [ [Object], [Object] ], [ [Object] ] ] }
team:
  - - bio: this is a test
      name: another test
    - bio: second item
      name: foo bar 2
  - - bio: another
      name: another
```
