### ISSUE TITLE
How can I prevent the user of block chomping indicators?

### ISSUE THREAD

**Issue by joker-777** [nodeca/js-yaml#495]
Hello,

I have a yaml file which looks like this

```yaml
- question:
    en: This is a very long question
      with multiple lines
```

When parsing it and returning it again, it looks like this

```yaml
- question:
    en: >-
      This is a very long question
      with multiple lines
```

How can I prevent using `>-`?
