### ISSUE TITLE
how to remove single quotation

### ISSUE THREAD

**Issue by cool-firer** [nodeca/js-yaml#511]
dump object:
```
const doc = {
  paths: {
    '/question/{type}/section': {
      get: { parameters: 123 },
    },
  },
};
fs.writeFileSync('test3.yaml', yaml.dump(doc));
```

what I expect:
```
paths:
  /question/{type}/section:
    get:
      parameters: 123

```
actually:
```
paths:
  '/question/{type}/section':
    get:
      parameters: 123
```
I dont want single quotation, how do I remove them?
