### ISSUE TITLE
Custom tag definition in schema config does not work

### ISSUE THREAD

**Issue by hakimio** [nodeca/js-yaml#520]
@GeekyDeaks 
According to [this Stack Overflow thread](https://stackoverflow.com/questions/40977113/js-yaml-issue-with-tags) it should be possible to add custom tag support by using `schema` config, but it doesn't seem to be working.
Yaml:
```yml
service:
  name: foo

custom:
  stage: ${opt:stage, self:provider.stage}
  common: ${file(../configs/common.yml):${self:custom.stage}}

provider:
  name: aws
  runtime: nodejs10.x
  region: ${self:custom.common.REGION}
  iamRoleStatements:
    - Effect: Allow
      Action: kinesis:PutRecord
      Resource: !ImportValue ApiEventsStreamArn-${self:custom.stage}

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: ${self:custom.common.API_PREFIX}/{proxy+}

```
Code which results in "Error: unknown tag !<!ImportValue>":
```js
    const yaml = require('js-yaml');

    const importValueYamlType = new yaml.Type('!ImportValue', { kind: 'mapping' }),
        refYamlType = new yaml.Type('!Ref', { kind: 'mapping' }),
        joinYamlType = new yaml.Type('!Join', { kind: 'mapping' }),
        schema = yaml.Schema.create([importValueYamlType, refYamlType, joinYamlType]);

    const result = yaml.load(content, { schema });
```
