### ISSUE TITLE
String "\n" shouldn't be serialized as a block scalar

### ISSUE THREAD

**Issue by Thom1729** [nodeca/js-yaml#534]
The string `"\n"` (containing one character, a newline) is serialized as a block scalar:

```yaml
|+


```

This is very awkward to read; it would be much clearer as a double-quoted string.

Also, it breaks my syntax highlighter. While this is undoubtedly a bug with the syntax highlighter, it must be admitted that YAML is very hard to highlight correctly and that js-yaml is not making it any easier in this case. It's also worth noting that the above Markdown code block was wrong the first time I typed it because Markdown ate the significant trailing newline.

This could be fixed in the `chooseScalarStyle` function. I'm not sure what would be a good general rule to avoid this; I'm open to suggestions.

**Comment by nejento** [comment]
I am now unsure if this is the issue, but let's say I have this:
```yaml
board:
  rows:
    6:
      interval: 5
      liner:
      - '
    7:
      interval: 80
      liner:
      - ''
    '8':
      interval: 80
      liner:
    '9':
      interval: 20
      liner:
    10:
      interval: 80
      liner:
      - ''
```

I'm getting a validated output:
```json
{
  "board": {
    "rows": {
      "6": {
        "interval": 5,
        "liner": [
          " 7: interval: 80 liner: - ' "
        ]
      },
      "9": {
        "interval": 20,
        "liner": null
      },
      "10": {
        "interval": 80,
        "liner": [
          ""
        ]
      },
      "8'": {
        "interval": 80,
        "liner": null
      }
    }
  }
}
```
However according to https://yaml-online-parser.appspot.com/ and the syntax highlighter it should not be validated:
```
ERROR:

while parsing a block mapping
  in "<unicode string>", line 3, column 5:
        6:
        ^
expected <block end>, but found '<scalar>'
  in "<unicode string>", line 11, column 6:
        '8':
         ^
```

Is there any way how to correct this?
