### ISSUE TITLE
Improve to "sortKeys" to allow sorting nesting containers last

### ISSUE THREAD

**Issue by octogonz** [nodeca/js-yaml#555]
Consider this input:

```yaml
- name: RootView
  title: noViewModel
  rect:
    height: 768
    width: 1024
    x: 0
    'y': 0
  scroll:
    scrollOffsetX: 0
    scrollOffsetY: 0
  ownerId: 0
  viewModelId: noViewModel
```

It would be nice if we could sort the keys alphabetically, except that keys with children should go last:

``` yaml
- name: RootView
  ownerId: 0
  title: noViewModel
  viewModelId: noViewModel
  rect:
    height: 768
    width: 1024
    x: 0
    'y': 0
  scroll:
    scrollOffsetX: 0
    scrollOffsetY: 0
```

This is similar to how a file explorer sorts files and folders separately.  Unfortunately the `js-yaml` API currently does not support this, because the `sortKeys` callback only receives an array of strings:

```js
  // Allow sorting keys so that the output file is deterministic
  if (state.sortKeys === true) {
    // Default sorting
    objectKeyList.sort();
  } else if (typeof state.sortKeys === 'function') {
    // Custom sort function
    objectKeyList.sort(state.sortKeys);
  } else if (state.sortKeys) {
    // Something is wrong
    throw new YAMLException('sortKeys must be a boolean or a function');
  }
```

It does not provide contextual information needed to look up the associated values for the keys.

Possible solutions:

- provide a specialized option: `sortKeysWithChildrenLast`

- pass a third parameter to the `sortKeys` function, something like this:
  ```js
  objectKeyList.sort(function(x,y) =>{
    return sortKeys(x, y, object);
  });
  ```
