### ISSUE TITLE
Can't resolve a JS function node

### ISSUE THREAD

**Issue by LJNeon** [nodeca/js-yaml#560]
This is the relevant snippet of my yml:
```yml
group: {
  cooldowns: [{
    aggressive: true,
    duration: 5e3,
    limit: 2
  }, {
    aggressive: true,
    duration: 2e4,
    limit: 20,
    sorter: !!js/function "msg => msg.channel.guild?.id ?? msg.channel.id"
  }]
}
```
I automatically load the yml using `yml.load(await fs.readFile(filePath, "utf8"))`, and in other yml files I use `!!js/regexp`, which works as expected. I thought it might be some issue with a character in the function, but wrapping it in `"`s doesn't change anything. I'm using Node.js v14.4.0 and the library is v3.14.0. I'll put the error below:
```
YAMLException: cannot resolve a node with !<tag:yaml.org,2002:js/function> explicit tag at line 59, column 82:
     ... nel.guild?.id ?? msg.channel.id"
                                         ^
    at generateError (/../node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/../node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at composeNode (/../node_modules/js-yaml/lib/js-yaml/loader.js:1426:9)
    at readFlowCollection (/../node_modules/js-yaml/lib/js-yaml/loader.js:746:7)
    at composeNode (/../node_modules/js-yaml/lib/js-yaml/loader.js:1360:11)
    at readFlowCollection (/../node_modules/js-yaml/lib/js-yaml/loader.js:735:5)
    at composeNode (/../node_modules/js-yaml/lib/js-yaml/loader.js:1360:11)
    at readFlowCollection (/../node_modules/js-yaml/lib/js-yaml/loader.js:746:7)
    at composeNode (/../node_modules/js-yaml/lib/js-yaml/loader.js:1360:11)
    at readBlockMapping (/../node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/../node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/../node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
    at loadDocuments (/../node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
    at Object.load (/../node_modules/js-yaml/lib/js-yaml/loader.js:1614:19)
    at loadData (file:///../services/data.js:131:23)
    at async file:///../src/index.js:47:3
