### ISSUE TITLE
dump with arrays

### ISSUE THREAD

**Issue by devsnek** [nodeca/js-yaml#582]
I have the following input:

```yaml
esid: sec-additional-properties-of-the-object.prototype-object
description: Behavior when "this" value is not extensible
info: |
    [...]
    5. Perform ? DefinePropertyOrThrow(O, key, desc).
features: [__defineGetter__]
```

I need add an item to the `features` array and output it in the same format. However this library outputs:

```yaml
esid: sec-additional-properties-of-the-object.prototype-object
description: Behavior when "this" value is not extensible
info: |
    [...]
    5. Perform ? DefinePropertyOrThrow(O, key, desc).
features:
  - __defineGetter__
  - proto-accessor
```

Is there a way to force it to look like `features: [__defineGetter__, proto-accessor]`?
