### ISSUE TITLE
expected a single document in the stream, but found more

### ISSUE THREAD

**Issue by cristianvasquez** [nodeca/js-yaml#589]

**Comment by cdll** [comment]
same issue here~
is it not support with these below?
```yaml
file-a:
  any: 123
---
file-b:
  own: 321
```
