### ISSUE TITLE
The 'load' function loads values of integer/boolean as string

### ISSUE THREAD

**Issue by buptliuhs** [nodeca/js-yaml#611]
Example of yaml file which contains integegers:

```
Resources:
  APIAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      MemorySize: 256
      Handler: api_auth/index.handler
      Runtime: nodejs12.x
      CodeUri: ../../functions/

```

In previous versions, e.g. 3.14.1, the 'load' function returns the following (integers **30/256** are **NOT** quoted, which are correct).
```
{
  "Resources": {
    "APIAuthFunction": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Timeout": 30,
        "MemorySize": 256,
        "Handler": "api_auth/index.handler",
        "Runtime": "nodejs12.x",
        "CodeUri": "../../functions/"
      }
    }
  }
}
```
In version 4.0.0, the 'load' function returns the following (integers **"30"/"256"** are **quoted**, which are **NOT** correct).
```
{
  "Resources": {
    "APIAuthFunction": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Timeout": "30",
        "MemorySize": "256",
        "Handler": "api_auth/index.handler",
        "Runtime": "nodejs12.x",
        "CodeUri": "../../functions/"
      }
    }
  }
}
```
Is this behaviour expected in 4.0.0? If yes, what is the reason behind that? Is that possible to load integer without quotes?

Thanks,
Tony
