### ISSUE TITLE
How to specify flow level of a specific element?

### ISSUE THREAD

**Issue by roipoussiere** [nodeca/js-yaml#613]
I have this data:

```json
{
  "dict": [
    {
      "foo": [
        "bar"
      ]
    }
  ],
  "array": [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
  ]
}
```

And I would like dump it like this:

```yaml
dict:
- foo:
  - bar
arrays:
- [1, 2, 3, 4, 5]
- [6, 7, 8, 9, 10]
```

Ie. indent all elements except `array` items.

I know I can use `flowLevel` to specify level of nesting, but how to apply it only for one item in data?
