### ISSUE TITLE
[reader] Heading spaces incorrectly parsed for some flow scalars

### ISSUE THREAD

**Issue by dervus** [nodeca/js-yaml#63]
This prints a warning, but shouldn't:

``` yaml
collection:
  block:
      "flow
   scalar" # JS-YAML warning: deficient indentation.
```

These are okay:

``` yaml
collection:
  block:
   "flow
   scalar" # Correct.
```

``` yaml
collection:
  block: "flow
   scalar" # Correct.
```
