### ISSUE TITLE
Ignoring/rejecting anchor and references in safeLoad

### ISSUE THREAD

**Issue by raubel** [nodeca/js-yaml#630]
Using the [Online Demo](http://nodeca.github.io/js-yaml/) with this small YAML content makes the page not responsive:
```yaml
lol1: &lol1 ["lol","lol","lol","lol","lol","lol","lol","lol","lol"]
lol2: &lol2 [*lol1,*lol1,*lol1,*lol1,*lol1,*lol1,*lol1,*lol1,*lol1]
lol3: &lol3 [*lol2,*lol2,*lol2,*lol2,*lol2,*lol2,*lol2,*lol2,*lol2]
lol4: &lol4 [*lol3,*lol3,*lol3,*lol3,*lol3,*lol3,*lol3,*lol3,*lol3]
lol5: &lol5 [*lol4,*lol4,*lol4,*lol4,*lol4,*lol4,*lol4,*lol4,*lol4]
lol6: &lol6 [*lol5,*lol5,*lol5,*lol5,*lol5,*lol5,*lol5,*lol5,*lol5]
lol7: &lol7 [*lol6,*lol6,*lol6,*lol6,*lol6,*lol6,*lol6,*lol6,*lol6]
lol8: &lol8 [*lol7,*lol7,*lol7,*lol7,*lol7,*lol7,*lol7,*lol7,*lol7]
lol9: &lol9 [*lol8,*lol8,*lol8,*lol8,*lol8,*lol8,*lol8,*lol8,*lol8]
lolz: &lolz [*lol9]
```

To avoid any deny of service on my web site, I would like __safeLoad__ to fail when the content to load contains references. Is that possible?
I tried with the FAILSAFE_SCHEMA (not sure it was the solution) but ended up with a JS error in `loader.js`.

I'm using **js-yaml 3.13.1**.

**Comment by puzrin** [comment]
https://github.com/nodeca/js-yaml/blob/master/index.js#L18-L21 you could use json schema instead, or construct your own, without merge type.

**Comment by raubel** [comment]
Thank you for the tip.

Unfortunately, using a JSON_SCHEMA gives me the same JS error as the FAILSAFE_SCHEMA. Here is the stack:
```
Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at composeNode (js-yaml.mjs:2582)
    at readBlockMapping (js-yaml.mjs:2194)
    at composeNode (js-yaml.mjs:2531)
    at readDocument (js-yaml.mjs:2715)
    at loadDocuments (js-yaml.mjs:2778)
    at load$1 (js-yaml.mjs:2804)
```
I tried both with **js-yaml 3.13.1** and **js-yaml 4.1.0**.

Here is my (typescript) code:
```typescript
import { JSON_SCHEMA, load } from 'js-yaml';

export const yamlLoad = (str: string): any => load(str, { schema: { include: [JSON_SCHEMA] } });
```

Am I misusing the API?

**Comment by puzrin** [comment]
I can not comment ts. This should work:

```js
const yaml = require('js-yaml')

console.log(yaml.load(your_input, { schema: yaml.JSON_SCHEMA }))
```

**Comment by raubel** [comment]
Indeed, it does work. Many thanks for your prompt replies.

**Comment by puzrin** [comment]
BTW, i guess, in demo problem is not with loader, but with output display.

**Comment by raubel** [comment]
Hi @puzrin,

Sorry for reopening this issue, but using `JSON_SCHEMA` does not reject anchors/references.

This code:
```typescript
import { MINIMAL_SCHEMA as SCHEMA, safeLoad } from 'js-yaml';

describe('load', () => {
  it('should fail when YAML contains references', () => {
    const yaml = `ref: &ref [*ref]`;
    const obj = safeLoad(yaml, { schema: SCHEMA });
    console.log(obj);
  });
});
```
procudes the output below:
```
{ ref: [ [Circular] ] }
```

Is there another schema type that would help?

**Comment by rlidwka** [comment]
> To avoid any deny of service on my web site, I would like safeLoad to fail when the content to load contains references. Is that possible?

Not possible IIRC, since anchors are basic yaml syntax.

The problem here is not in the parser itself, but in JSON.stringify-like function used to display the document.

If you are worried about documents that reference themselves, you can check for them explicitly using something like this:

```js
function parse_yaml(text) {
  const result = require('js-yaml').load(text); // or safeLoad in 3.x

  const get_replacer = () => {
    const seen = new WeakSet();

    return (key, value) => {
      if (typeof value === "object" && value !== null) {
        if (seen.has(value)) throw new Error('circular reference');
        seen.add(value);
      }
      return value;
    };
  };

  // this will fail on documents with back references
  JSON.stringify(result, get_replacer());

  return result;
}
```

Code above is adapted from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value#examples

**Comment by raubel** [comment]
Thank you, @rlidwka.

My problem is not only circular objects, but also huge objects that could be loaded from YAML like this:
```yaml
lol1: &lol1 ["lol","lol","lol","lol","lol","lol","lol","lol","lol"]
lol2: &lol2 [*lol1,*lol1,*lol1,*lol1,*lol1,*lol1,*lol1,*lol1,*lol1]
lol3: &lol3 [*lol2,*lol2,*lol2,*lol2,*lol2,*lol2,*lol2,*lol2,*lol2]
lol4: &lol4 [*lol3,*lol3,*lol3,*lol3,*lol3,*lol3,*lol3,*lol3,*lol3]
lol5: &lol5 [*lol4,*lol4,*lol4,*lol4,*lol4,*lol4,*lol4,*lol4,*lol4]
lol6: &lol6 [*lol5,*lol5,*lol5,*lol5,*lol5,*lol5,*lol5,*lol5,*lol5]
lol7: &lol7 [*lol6,*lol6,*lol6,*lol6,*lol6,*lol6,*lol6,*lol6,*lol6]
lol8: &lol8 [*lol7,*lol7,*lol7,*lol7,*lol7,*lol7,*lol7,*lol7,*lol7]
lol9: &lol9 [*lol8,*lol8,*lol8,*lol8,*lol8,*lol8,*lol8,*lol8,*lol8]
lolz: &lolz [*lol9]
```
As the `load` function needs to parse YAML syntax, I would expect it to be able to provide this feature (rejecting anchors/references).

As you have suggested, without this facility, I will have to inspect my object once loaded for circular references and size.
