### ISSUE TITLE
Ignore Custom Tags

### ISSUE THREAD

**Issue by fjogeleit** [nodeca/js-yaml#636]
Hey everyone,

I'm using this library for my GitHub Action (https://github.com/fjogeleit/yaml-update-action) to update values of yaml files in CI/CD pipelines and this library works really good so far.

One problem one of my users is facing are custom tags. His yaml looks like this:

```yaml
markdown_extensions:
    - markdown_fenced_code_tabs:
        template: "bootstrap4"
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
```

I found an answer in a previous issue how I can create a CustomTag to process all kind of this custom tags. This solution has one downside in this case. The resulting YAML set quotes around the tag like this:

```yaml
markdown_extensions:
    - markdown_fenced_code_tabs:
        template: "bootstrap4"
    - pymdownx.emoji:
        emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
```

So the tag will not be processed in later steps.

Is it possible to configure a schema to ignore every tag? Also the build in ones? Because I don't need any of them in my case.

Thanks in advance

**Comment by rlidwka** [comment]
> This solution has one downside in this case. The resulting YAML set quotes around the tag like this:

There's no quotes around tag name, see an example:

```js
'use strict';

/*eslint-disable no-console*/

const util = require('util');
const yaml = require('../');


class CustomTag {
  constructor(type, data) {
    this.type = type;
    this.data = data;
  }
}


const tags = [ 'scalar', 'sequence', 'mapping' ].map(function (kind) {
  // first argument here is a prefix, so this type will handle anything starting with !
  return new yaml.Type('tag:', {
    kind: kind,
    multi: true,
    representName: function (object) {
      return object.type;
    },
    represent: function (object) {
      return '';

    },
    instanceOf: CustomTag,
    construct: function (data, type) {
      return new CustomTag(type, data);
    }
  });
});

const SCHEMA = yaml.DEFAULT_SCHEMA.extend(tags);

const data = `
markdown_extensions:
    - markdown_fenced_code_tabs:
        template: "bootstrap4"
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
`;

const loaded = yaml.load(data, { schema: SCHEMA });

console.log('Parsed as:');
console.log('-'.repeat(70));
console.log(util.inspect(loaded, false, 20, true));

console.log('');
console.log('');
console.log('Dumped as:');
console.log('-'.repeat(70));
console.log(yaml.dump(loaded, { schema: SCHEMA }));
```

outputs this:

```
Parsed as:
----------------------------------------------------------------------
{
  markdown_extensions: [
    { markdown_fenced_code_tabs: { template: 'bootstrap4' } },
    {
      'pymdownx.emoji': {
        emoji_generator: CustomTag {
          type: 'tag:yaml.org,2002:python/name:pymdownx.emoji.to_svg',
          data: null
        }
      }
    }
  ]
}


Dumped as:
----------------------------------------------------------------------
markdown_extensions:
  - markdown_fenced_code_tabs:
      template: bootstrap4
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg ''
```

**Comment by fjogeleit** [comment]
thanks for your example @rlidwka, I found the reason for my issue but there is another one which is also visible in your example:

```yaml
markdown_extensions:
  - markdown_fenced_code_tabs:
      template: bootstrap4
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg ''
```

There are empty single quotes in the end of the CustomTag string

> emoji_generator: !!python/name:pymdownx.emoji.to_svg **''**
