### ISSUE TITLE
Variables reference

### ISSUE THREAD

**Issue by lfernando2091** [nodeca/js-yaml#641]
Example:
```yaml
environments:
  myVar: Hola
  
use:
  case1: ${environments.myVar}  Mundo
  case2: ${environments.myVar}s Buenos Dias
```
Result
```bash
> print use.case1
Hola Mundo

> print use.case2
Holas Buenos Dias
```
