### ISSUE TITLE
How do you generate a YAML file with comments?

### ISSUE THREAD

**Issue by octogonz** [nodeca/js-yaml#642]
We have a tool that generates YAML config files for CI pipelines.

The files contain informative code comments.  Here's a representative example (with a bunch of fields deleted for brevity):

```yaml
# DO NOT EDIT THIS FILE!!!
# To modify this file, make changes to the associated config files
# and then invoke the "generate-pipelines" tool.
variables:
  - name: NodeVersion
    value: 12
jobs:
  - job: PRBuild
    condition: succeeded()
    steps:
      - checkout: self
        fetchDepth: 1
        lfs: true
        
      - script: 'node common/scripts/install-run-rush.js install'
        displayName: 'Install Rush'
        
      - script: 'node common/scripts/install-run-rush.js rebuild'
        displayName: 'AWS Pipelines Check'
        
      # Generated from 'apps/example-app/infra/production/aws-stacks.json'
      - task: CloudFormationCreateOrUpdateStack@1 
        inputs:
          templateFile: 'common/config/aws/templates/bucket.cf.json'

          # Below parameter(s) generated from 1 file(s)
          # apps/example-app/infra/production/bucket-provision.cf-params.json
          templateParameters: | 
            -
              ParameterKey: 'BucketName'
              ParameterValue: 'example-app.example.com'
            -
              ParameterKey: 'CostOwner'
              ParameterValue: 'example-app'
            -
              ParameterKey: 'CostService'
              ParameterValue: 'example-app.example.com'
          capabilityAutoExpand: true
          onFailure: 'DELETE'
          
      # Generated from 'apps/example-app/infra/production/aws-stacks.json'
      - task: CloudFormationCreateOrUpdateStack@1 
        inputs:
          awsCredentials: 'AWS Production'
          regionName: 'us-east-1'
```

As you can see, the comments aren't merely pasted at the top of the file, they need to appear inline in the file as well.  

We started using a simple string template, but it is tricky to escape parameters correctly.  The [js-yaml](https://www.npmjs.com/package/js-yaml) project seems like a better solution.

But does the `yaml.dump()` API provide some way to inject comment strings?

Comments are a core feature of YAML, so it seems that there should be some way to do that.  Thanks!

CC @hbo-iecheruo
