### ISSUE TITLE
Redundant quotes added  

### ISSUE THREAD

**Issue by coderaiser** [nodeca/js-yaml#645]
```js
const yaml = require('js-yaml');

const file = `
  name: Node CI
  on:
    - push
`;

const json = yaml.load(file);
console.log(yaml.dump(json));
```

Output:

```yaml
name: Node CI
'on':
  - push
```
