### ISSUE TITLE
Generating anchor references for simple string values

### ISSUE THREAD

**Issue by atava** [nodeca/js-yaml#651]
I know that the library generates anchors/aliases for same-reference objects, but I would like to avoid the repetition of string values without having to wrap them in objects.

Is this possible?

e.g.
```
rule1:
  reference: A1
  text: Some very long text.
rule2:
  reference: B1
  text: Some very long text.
```
to
```
rule1: 
  reference: A1
  text: &ref1 "Some very long text."
rule2: 
  reference: B1
  text: *ref1
```
