### ISSUE TITLE
js-yaml is susceptible to a YAML bomb

### ISSUE THREAD

**Issue by mefellows** [nodeca/js-yaml#652]
Hi team,

Thanks for the great library!

Given the following `bomb.yaml` file, which is a [YAML bomb](https://en.wikipedia.org/wiki/Billion_laughs_attack):

```yaml
# lol-one is a single laugh:
lol1: &lol1 "lol"
# a var, an anchor, and a value, remember?

# lol-2 is an array of 10 lol-one's:
lol2: &lol2 [*lol1, *lol1, *lol1, *lol1, *lol1, *lol1, *lol1, *lol1, *lol1]
# a var, an anchor and a value.
# the value just happened to be an array of 10 anchors to lol1.
# thats completely legal in yaml.

# an array of 10 arrays of 10 laughs: (right, thats 100 laughs)
lol3: &lol3 [*lol2, *lol2, *lol2, *lol2, *lol2, *lol2, *lol2, *lol2, *lol2]

# well, you got the idea:
lol4: &lol4 [*lol3, *lol3, *lol3, *lol3, *lol3, *lol3, *lol3, *lol3, *lol3]
lol5: &lol5 [*lol4, *lol4, *lol4, *lol4, *lol4, *lol4, *lol4, *lol4, *lol4]
lol6: &lol6 [*lol5, *lol5, *lol5, *lol5, *lol5, *lol5, *lol5, *lol5, *lol5]
lol7: &lol7 [*lol6, *lol6, *lol6, *lol6, *lol6, *lol6, *lol6, *lol6, *lol6]
lol8: &lol8 [*lol7, *lol7, *lol7, *lol7, *lol7, *lol7, *lol7, *lol7, *lol7]
lol9: &lol9 [*lol8, *lol8, *lol8, *lol8, *lol8, *lol8, *lol8, *lol8, *lol8]
lol10: &lol10 [*lol9, *lol9, *lol9, *lol9, *lol9, *lol9, *lol9, *lol9, *lol9]
```

Running `js-yaml ./bomb.yml` will take a long time, and carefully monitoring the system resources will show it starts to consume a reasonable amount of memory. On my reasonable powerful Mac, it eventually crashes after 45s:

```
/private/tmp/yaml-bomb/node_modules/js-yaml/bin/js-yaml.js:124
  if (isYaml) console.log(JSON.stringify(output, null, '  '));
                               ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at /private/tmp/yaml-bomb/node_modules/js-yaml/bin/js-yaml.js:124:32
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
./node_modules/.bin/js-yaml ./bomb.yml  44.64s user 8.73s system 102% cpu 52.173 total
```

This makes the library unsuitable for various production use cases. 

**Solution**

The suggested fix is to keep track of the alias count and limit the number of aliases for non-scalar nodes (e.g. to a maximum of 50). See also https://snyk.io/blog/java-yaml-parser-with-snakeyaml/
