### ISSUE TITLE
Parsing yaml file having dynamic field problem

### ISSUE THREAD

**Issue by hasanwhitesource** [nodeca/js-yaml#656]
For example im trying to read this yaml file : 
```
releases:
  - name:  "external-dns"
    chart: "bitnami/external-dns"
    namespace: "external-dns"
    version: {{ .Values | getOrNil "external_dns.version" | default "4.5.5" }}
    installed: {{ .Values | getOrNil "external_dns.installed" | default false }}
```

I'm expecting to read version and the installed fields as string by using `loadAll` but I'm getting them back as null. Is there a proper way to read these values ?
