### ISSUE TITLE
how to dump insert blank line?

### ISSUE THREAD

**Issue by yanhaijing** [nodeca/js-yaml#662]
```js
const yml = yaml.dump(object, options);
fs.writeFileSync(saberpath, yml);
```

The results are shown below

```yml
stages:
  - install
  - test
  - sonar
  - build
install:
  stage: install
  image: node:14.19.0
  script:
    - yarn
  artifacts:
    name: install
lint:
  stage: test
  image: node:14.19.0
``` 

Here's what I'd like to see, how do I insert blank lines between blocks

```yml
stages:
  - install
  - test
  - sonar
  - build
 
install:
  stage: install
  image: node:14.19.0
  script:
    - yarn
  artifacts:
    name: install

lint:
  stage: test
  image: node:14.19.0
```
