### ISSUE TITLE
JSON to YAML - possible to set dump as frontmatter?

### ISSUE THREAD

**Issue by jasonday** [nodeca/js-yaml#670]
I'm using the library to take an API response and create YAML. 

```
results.forEach(result => {
        let name = result[args.name];
        let cleaned = cleanName(name);
        let yamlStr = yaml.dump(result);
        fs.writeFileSync(args.dir + '/' + cleaned + '.md', yamlStr, 'utf8');
        console.log(cleaned + ".yml created");
    });
```

Which works great. I get:
```
_id: 5d487c2e3235325615000237
description: A message with important, and usually time-sensitive, information.
notes:
  - field:
      type: text
```

But I'd like to output like below, specifying "description" as the body of the frontmatter:
```
---
_id: 5d487c2e3235325615000237
notes:
  - field:
      type: text
---
A message with important, and usually time-sensitive, information.
```
