### ISSUE TITLE
merged arrays 

### ISSUE THREAD

**Issue by cl0ckwork** [nodeca/js-yaml#688]
I believe yaml array merge is broken, might be a trivial fix, but i have not looked at the implementation. here is an example from [the online demo
](https://nodeca.github.io/js-yaml/#yaml=LS0tCiMgQ29sbGVjdGlvbiBUeXBlcyAjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjCiMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjCgojIGh0dHA6Ly95YW1sLm9yZy90eXBlL21hcC5odG1sIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIwoKZXhhbXBsZV9hcnJheTogJmV4YW1wbGVfYXJyYXkKIC0gb25lCiAtIHR3bwogCnNwcmVhZF9hcnJheToKICAtIGZpdmUKICAtIGZvdXIKICAtICpleGFtcGxlX2FycmF5Cgo=)

```yaml
example_array: &example_array
 - one
 - two
 
spread_array:
  - five
  - four
  - *example_array
```

result
```js
{ example_array: [ 'one', 'two' ],
  spread_array: [ 'five', 'four', [ 'one', 'two' ] ] }
```

expected 
```js
{ example_array: [ 'one', 'two' ],
  spread_array: [ 'five', 'four', 'one', 'two' ] }
```
