### ISSUE TITLE
ugly dumping of arrays

### ISSUE THREAD

**Issue by Morriz** [nodeca/js-yaml#690]
Hi, we see that dumping
```json
{
  "someArr": [{"some": "prop", "another": "prop"}]
}
```

results in arrays looking like:
```yaml
-
  some: prop
  another: prop
```

How could we get it to dump like this:
```yaml
- some: prop
  another: prop
```
?
