### ISSUE TITLE
Object with empty properties gets {} as a value

### ISSUE THREAD

**Issue by sosadchuk** [nodeca/js-yaml#694]
Hi,

I'm converting JSON to YAML, input looks like the following:
```
{
  "version": 1,
  "strategyOperationsStatisticsSummary": {
    "totals": {
      "drops": 0,
      "creates": 0,
      "alters": 0
    }
  },
  "strategyObjectListsDetail": {},
  "strategyAndAnalysisOptions": {
    "strategyType": "compare",
    "strategyName": "CMPRSTRT",
    "strategyCreator": "USERID",
    "srcImportDataset": "USERID.CMPDDL.JOB68250.D0000101.?",
    "trgSSID": "SSID"
  }
}
```

`JSON.parse()` creates an object with property `strategyObjectListsDetail` as an object without any properties.

The following js-yaml `dump()` produces output:
```
version: 1
strategyOperationsStatisticsSummary:
  totals:
    drops: 0
    creates: 0
    alters: 0
strategyObjectListsDetail: {}
strategyAndAnalysisOptions:
  strategyType: compare
  strategyName: CMPRSTRT
  strategyCreator: USERID
  srcImportDataset: USERID.CMPDDL.JOB68250.D0000101.?
  trgSSID: SSID
```

You can see the `strategyObjectListsDetail` property literally having the value of `{}`. I wonder if that's ok, because it feels more correct to have it as an empty value like:
```
strategyObjectListsDetail:
```

Thanks,
Sergei.
