### ISSUE TITLE
export anchors(refs)

### ISSUE THREAD

**Issue by lucasyarid** [nodeca/js-yaml#718]
Is there any way I can access YAML anchors?
Take this example:
```yaml
shared: &shared
  - common/**/*
  - config/**/*
src:
  - *shared
  - src/**/*
backend:
  - '!(**/*.tsx|**/*.less)'
 ```

If I ran `load` on it, I get:
```javascript
{
  shared: [ 'common/**/*', 'config/**/*' ],
  src: [ [ 'common/**/*', 'config/**/*' ], 'src/**/*' ],
  backend: [ '!(**/*.tsx|**/*.less)' ]
}
```

Which is expected but there is no way for me to know which of these keys are anchors or not.
