### ISSUE TITLE
Blocks made with pipes have a leading new line while dumping

### ISSUE THREAD

**Issue by sujeeet-kumar** [nodeca/js-yaml#721]
```js
const yaml = require('js-yaml');

// Sample data
const pipelineData = {
    appName: "sample-app",
    eksEnv: "dev",
    secretProviderClass: {
        parameters: {}
    }
};

const jmesPathEntries = [
    { path: "CONFIG_services_postgres_password", objectAlias: "postgres_password" }
];

// Build the objects section with proper formatting
pipelineData.secretProviderClass.parameters.objects = `|\n  - objectName: "ktp/${pipelineData.appName}/${pipelineData.eksEnv}/secrets"\n    objectType: "secretsmanager"\n    jmesPath:\n${jmesPathEntries.map(entry => `    - path: ${entry.path}\n      objectAlias: ${entry.objectAlias}`).join('\n')}`;

// Convert to YAML
const yamlStr = yaml.dump(pipelineData.secretProviderClass.parameters);

console.log(yamlStr);

```
### Output
```yaml
parameters:
  objects: "|\n  - objectName: \"domain/sample-app/dev/secrets\"\n    objectType: \"secretsmanager\"\n    jmesPath:- path: CONFIG_services_postgres_password \r\n objectAlias: postgres_password"
```
### Expected Output:
```yaml
parameters:
  objects: |
    - objectName: "domain/sample-app/dev/secrets"
      objectType: "secretsmanager"
      jmesPath:
      - path: CONFIG_services_postgres_password
        objectAlias: postgres_password
```
