### ISSUE TITLE
Feature Request: Option to keep use `|-` while using forceQuotes

### ISSUE THREAD

**Issue by rinsuki** [nodeca/js-yaml#726]
personally I prefer to use quotes for string in YAML, rather than raw strings, to keep avoid confuses around number, like this:

```yaml
app:
  version: 1.2.3 # => string
pg:
  version: 15.2 # => edited by human and now its number, but unexpected...
```

in js-yaml, this can be done with `forceQuotes` option for `yaml.dump()`, but this also disables `|-` syntax.

```yaml
app:
  version: '1.2.3' # this is string, really clear
  startup: "#!/bin/bash\n# doing something\n# also doing something..." # ... hard to read
```

since `|` defines they are always string (like quotes does), it would be good to have option to also allow their (aka just simply disallows implicit string literal)

Expected Result:
```yaml
app:
  version: '1.2.3'
  startup: |-
    #!/bin/bash
    # doing something
    # also doing something...
```
